### ISSUE TITLE
crash in nodeObjs/noMovable.cpp

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1054]
Before this happend, I had another crash. But since the games has been very stable I gave up my habit of always playing through gdb. Only this message from dmesg - `traps: s25client[24248] trap int3 ip:732db5 sp:7ffd316ea320 error:0`

I tried to provoke it again. I have the game on speed 4 or 5, fast or very fast, and I kind of noticed a lag of a few seconds when destroying buildings or setting flags for instance. It was a lot more noticeable on speed 5. And then suddenly, it crashed again: 

```

Thread 1 "s25client" received signal SIGTRAP, Trace/breakpoint trap.
0x0000000000732db5 in noMovable::CalcRelative (this=0x3ca3680, curPt=..., nextPt=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/nodeObjs/noMovable.cpp:139
139	/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/nodeObjs/noMovable.cpp: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x0000000000732db5 in noMovable::CalcRelative (this=0x3ca3680, curPt=..., nextPt=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/nodeObjs/noMovable.cpp:139
#1  0x0000000000687419 in noFigure::CalcFigurRelative (this=0x3ca3680) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/figures/noFigure.cpp:218
#2  0x0000000000688c3e in noFigure::DrawWalkingBobJobs (this=0x3ca3680, drawPt=..., job=6)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/figures/noFigure.cpp:784
#3  0x000000000068912b in noFigure::DrawWalking (this=0x3ca3680, drawPt=...) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/figures/noFigure.cpp:842
#4  0x0000000000692ca0 in nofBuildingWorker::Draw (this=0x3ca3680, drawPt=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/figures/nofBuildingWorker.cpp:102
#5  0x00000000005b7ded in GameWorldView::DrawFigures (this=<optimized out>, pt=..., curPos=..., between_lines=std::vector of length 2, capacity 2 = {...})
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/world/GameWorldView.cpp:445
#6  0x00000000005b7373 in GameWorldView::Draw (this=<optimized out>, rb=..., selected=..., drawMouse=true, water=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/world/GameWorldView.cpp:182
#7  0x0000000000671ad5 in dskGameInterface::Run (this=0x52a8750) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/desktops/dskGameInterface.cpp:885
#8  0x000000000067160e in dskGameInterface::Msg_PaintBefore (this=0x52a8750)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/desktops/dskGameInterface.cpp:274
#9  0x000000000051f078 in WindowManager::Draw (this=0xc95f50) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/WindowManager.cpp:75
#10 0x000000000050796d in GameManager::Run (this=0xc79d90) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/GameManager.cpp:153
#11 0x00000000004f8894 in RunProgram (options=...) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25client/s25client.cpp:391
#12 0x00000000004f8c1b in main (argc=<optimized out>, argv=<optimized out>) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25client/s25client.cpp:446
```
and
```
(gdb) continue
Continuing.
Assertion failure in "CalcRelative" at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/nodeObjs/noMovable.cpp#139: IsMoving() || IsStoppedBetweenNodes()
```

**Comment by stefson** [comment]
this should be the correct replay: [2019-03-20_00-18-43.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/2985931/2019-03-20_00-18-43.rpl.zip)

**Comment by stefson** [comment]
another crash with the same backtrace: [2019-03-20_09-17-53.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/2987245/2019-03-20_09-17-53.rpl.zip)

**Comment by stefson** [comment]
Can't build a lookout tower, right on that position where the mouse is hovered in that screenshot: 

![2019-03-23-101504_1680x1050_scrot](https://user-images.githubusercontent.com/14232936/54864243-ea990800-4d54-11e9-8eca-310597321b05.png)


[save+replay.zip](https://github.com/Return-To-The-Roots/s25client/files/2999182/save%2Breplay.zip)

**Comment by Flamefire** [comment]
> Can't build a lookout tower, right on that position where the mouse is hovered in that screenshot:

Why? What is the problem? Is this related to this issue?

**Comment by stefson** [comment]
I certainly don't know why, yet it might be related to this issue since the building of objects had been greatly delayed before. If you're not convinced I'll open a new issue and delete that post, no problem.

**Comment by Flamefire** [comment]
No the question was: This issue is about an assertion failure. You say you can't build a lookout tower. What happens when you try? The same assertion failure? Crash? Nothing at all?

**Comment by stefson** [comment]
Ah, okay. Actually nothing happens at all. No crash, no assertion failure, nothing.

**Comment by Flamefire** [comment]
Ok then this is unrelated. Moved to #1055

**Comment by Flamefire** [comment]
No longer an issue on current master

**Comment by stefson** [comment]
hit it again today: 

```
Thread 1 "s25client" received signal SIGTRAP, Trace/breakpoint trap.
0x000055555586ee42 in noMovable::CalcRelative (this=this@entry=0x555559b281e0, curPt=curPt@entry=..., nextPt=nextPt@entry=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/nodeObjs/noMovable.cpp:139
139	/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/nodeObjs/noMovable.cpp: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x000055555586ee42 in noMovable::CalcRelative (this=this@entry=0x555559b281e0, curPt=curPt@entry=..., nextPt=nextPt@entry=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/nodeObjs/noMovable.cpp:139
#1  0x000055555577e1e4 in noFigure::CalcFigurRelative (this=this@entry=0x555559b281e0)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/figures/noFigure.cpp:216
#2  0x000055555577fc00 in noFigure::DrawWalkingBobJobs (this=this@entry=0x555559b281e0, drawPt=..., job=6)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/figures/noFigure.cpp:781
#3  0x0000555555780031 in noFigure::DrawWalking (this=0x555559b281e0, drawPt=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/figures/noFigure.cpp:839
#4  0x000055555578d4df in nofBuildingWorker::Draw (this=<optimized out>, drawPt=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/figures/nofBuildingWorker.cpp:91
#5  0x000055555569b802 in GameWorldView::DrawFigures (this=this@entry=0x55555b2b61d0, pt=..., curPos=..., between_lines=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/world/GameWorldView.cpp:443
#6  0x000055555569d4e3 in GameWorldView::Draw (this=0x55555b2b61d0, rb=..., selected=..., drawMouse=<optimized out>, water=water@entry=0x7fffffffd54c)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/world/GameWorldView.cpp:180
#7  0x000055555576409e in dskGameInterface::Run (this=this@entry=0x55555b2b5f20)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/ingameWindows/iwAction.h:86
#8  0x00005555557641dc in dskGameInterface::Msg_PaintBefore (this=0x55555b2b5f20)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/desktops/dskGameInterface.cpp:273
#9  0x00005555555e89c0 in WindowManager::Draw (this=0x555555c27330) at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/WindowManager.cpp:87
#10 0x00005555555c8309 in GameManager::Run (this=0x7fffffffd800) at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/GameManager.cpp:157
#11 0x00005555555b9bca in (anonymous namespace)::RunProgram (options=...) at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25client/s25client.cpp:401
#12 0x00005555555b9f46 in main (argc=<optimized out>, argv=0x7fffffffdce8) at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25client/s25client.cpp:477
(gdb) continue
Continuing.
Assertion failure in "CalcRelative" at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/nodeObjs/noMovable.cpp#139: IsMoving() || IsStoppedBetweenNodes()
```
[2020-06-07_16-54-51.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/4742352/2020-06-07_16-54-51.rpl.zip)
[2020-06-07_16-54-35.log.zip](https://github.com/Return-To-The-Roots/s25client/files/4742353/2020-06-07_16-54-35.log.zip)

**Comment by Flamefire** [comment]
--> #1126
