### ISSUE TITLE
Assertion failure in SimpleFindPosition

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1127]
```
Thread 1 "s25client" received signal SIGTRAP, Trace/breakpoint trap.
0x0000000000769a4c in AIJH::AIPlayerJH::SimpleFindPosition (this=0x128f1f0, pt=..., 
    size=BQ_CASTLE, radius=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:1025
1025	/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x0000000000769a4c in AIJH::AIPlayerJH::SimpleFindPosition (this=0x128f1f0, pt=..., size=BQ_CASTLE, radius=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:1025
#1  0x0000000000769e49 in AIJH::AIPlayerJH::FindPositionForBuildingAround (this=0x128f1f0, type=BLD_PIGFARM, around=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:1051
#2  0x000000000077c6dd in AIJH::BuildJob::TryToBuild (this=0x4c0a790) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/Jobs.cpp:111
#3  0x000000000077c5a6 in AIJH::BuildJob::ExecuteJob (this=0x4c0a790) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/Jobs.cpp:48
#4  0x0000000000789e7c in AIJH::AIConstruction::ExecuteJobs (this=0x3aa94d0, limit=10)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIConstruction.cpp:134
#5  0x0000000000764775 in AIJH::AIPlayerJH::ExecuteAIJob (this=0x128f1f0) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:819
#6  0x0000000000764010 in AIJH::AIPlayerJH::RunGF (this=0x128f1f0, gf=161990, gfisnwf=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:203
#7  0x0000000000575c61 in GameClient::NextGF (this=0x1241b90, wasNWF=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:1321
#8  0x0000000000571ba5 in GameClient::ExecuteGameFrame (this=0x1241b90) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:1259
#9  0x0000000000571805 in GameClient::Run (this=0x1241b90) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:182
#10 0x0000000000502076 in GameManager::Run (this=0xac1690) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/GameManager.cpp:113
#11 0x00000000004f1374 in (anonymous namespace)::RunProgram (options=...) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25client/s25client.cpp:382
#12 0x00000000004f10c0 in main (argc=<optimized out>, argv=<optimized out>) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25client/s25client.cpp:440
(gdb) continue
Assertion failure in "SimpleFindPosition" at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp#1.025: aii.GetBuildingQuality(curPt) == GetAINode(curPt).bq
```

replay: [2019-11-01_13-12-29.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/3797848/2019-11-01_13-12-29.rpl.zip)

**Comment by stefson** [comment]
```
Thread 1 "s25client" received signal SIGTRAP, Trace/breakpoint trap.
0x00005555558a8d1a in AIJH::AIPlayerJH::SimpleFindPosition (this=0x5555561d63a0, pt=..., size=size@entry=BQ_HARBOR, radius=radius@entry=11)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:1025
1025	/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x00005555558a8d1a in AIJH::AIPlayerJH::SimpleFindPosition (this=0x5555561d63a0, pt=..., size=size@entry=BQ_HARBOR, radius=radius@entry=11)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:1025
#1  0x00005555558a938c in AIJH::AIPlayerJH::FindPositionForBuildingAround (this=0x5555561d63a0, type=BLD_HARBORBUILDING, around=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/array:189
#2  0x00005555558b84e2 in AIJH::BuildJob::TryToBuild (this=this@entry=0x55555e7f8710)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/Jobs.cpp:111
#3  0x00005555558b8d40 in AIJH::BuildJob::ExecuteJob (this=0x55555e7f8710) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/Jobs.cpp:48
#4  0x00005555558d0246 in AIJH::AIConstruction::ExecuteJobs (this=0x55555c0c6730, limit=40)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIConstruction.cpp:134
#5  0x00005555558a3e0d in AIJH::AIPlayerJH::ExecuteAIJob (this=this@entry=0x5555561d63a0)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:819
#6  0x00005555558aee4f in AIJH::AIPlayerJH::RunGF (this=this@entry=0x5555561d63a0, gf=212988, gfisnwf=gfisnwf@entry=true)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:203
#7  0x0000555555650f9b in GameClient::NextGF (this=this@entry=0x55555623ca30, wasNWF=wasNWF@entry=true)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:1321
#8  0x000055555565992d in GameClient::ExecuteGameFrame (this=this@entry=0x55555623ca30)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:1259
#9  0x000055555565a01f in GameClient::Run (this=0x55555623ca30) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:182
#10 0x00005555555cf81d in GameManager::Run (this=0x555555ac60f0)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/libs/common/include/s25util/SingletonImp.hpp:72
#11 0x00005555555bec69 in (anonymous namespace)::RunProgram (options=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/libs/common/include/s25util/SingletonImp.hpp:72
#12 0x00005555555befdc in main (argc=<optimized out>, argv=0x7fffffffdc78) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25client/s25client.cpp:440
(gdb) continue
Continuing.
Assertion failure in "SimpleFindPosition" at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp#1.025: aii.GetBuildingQuality(curPt) == GetAINode(curPt).bq
```
replay: [2019-11-10_22-03-56.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/3829050/2019-11-10_22-03-56.rpl.zip)
