### ISSUE TITLE
Assertion failure in ConnectFlagToRoadSytem

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1128]
```
Thread 1 "s25client" received signal SIGTRAP, Trace/breakpoint trap.
0x00005555558d8b80 in AIJH::AIConstruction::ConnectFlagToRoadSytem (
    this=this@entry=0x55555a4f5490, flag=flag@entry=0x55555823e2c0, route=..., 
    maxSearchRadius=maxSearchRadius@entry=14)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIConstruction.cpp:331
331	/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIConstruction.cpp: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x00005555558d8b80 in AIJH::AIConstruction::ConnectFlagToRoadSytem (this=this@entry=0x55555a4f5490, flag=flag@entry=0x55555823e2c0, route=..., 
    maxSearchRadius=maxSearchRadius@entry=14) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIConstruction.cpp:331
#1  0x00005555558bfdca in AIJH::BuildJob::BuildMainRoad (this=this@entry=0x555558b83f60)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/Jobs.cpp:213
#2  0x00005555558c0070 in AIJH::BuildJob::ExecuteJob (this=0x555558b83f60) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/Jobs.cpp:50
#3  0x00005555558d82a2 in AIJH::AIConstruction::ExecuteJobs (this=0x55555a4f5490, limit=23)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIConstruction.cpp:134
#4  0x00005555558ab3ff in AIJH::AIPlayerJH::ExecuteAIJob (this=this@entry=0x555558108ec0)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:819
#5  0x00005555558b6362 in AIJH::AIPlayerJH::RunGF (this=this@entry=0x555558108ec0, gf=196017, gfisnwf=gfisnwf@entry=true)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:203
#6  0x000055555564f1ab in GameClient::NextGF (this=this@entry=0x5555562a7780, wasNWF=wasNWF@entry=true)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:1321
#7  0x0000555555656571 in GameClient::ExecuteGameFrame (this=this@entry=0x5555562a7780)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:1259
#8  0x0000555555656cdd in GameClient::Run (this=0x5555562a7780) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:182
#9  0x00005555555cf89f in GameManager::Run (this=0x555555b2fe90)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/include/libutil/SingletonImp.hpp:72
#10 0x00005555555bed01 in (anonymous namespace)::RunProgram (options=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/include/libutil/SingletonImp.hpp:72
#11 0x00005555555bf074 in main (argc=1, argv=0x7fffffffdc68) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25client/s25client.cpp:440
(gdb) continue
Continuing.
Assertion failure in "ConnectFlagToRoadSytem" at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIConstruction.cpp#331: aii.GetBuildingQuality(tmpPos) == aijh.GetAINode(tmpPos).bq
```
replay: [2019-11-01_17-26-45.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/3798760/2019-11-01_17-26-45.rpl.zip)

**Comment by stefson** [comment]
hit it again: 

```

Thread 1 "s25client" received signal SIGTRAP, Trace/breakpoint trap.
0x00005555558d0c71 in AIJH::AIConstruction::ConnectFlagToRoadSytem (
    this=this@entry=0x55555e6968d0, flag=flag@entry=0x55555a840f10, route=..., 
    maxSearchRadius=maxSearchRadius@entry=24)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIConstruction.cpp:331
331	/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIConstruction.cpp: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x00005555558d0c71 in AIJH::AIConstruction::ConnectFlagToRoadSytem (this=this@entry=0x55555e6968d0, flag=flag@entry=0x55555a840f10, route=..., 
    maxSearchRadius=maxSearchRadius@entry=24) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIConstruction.cpp:331
#1  0x00005555558b7e7c in AIJH::ConnectJob::ExecuteJob (this=0x555558235670) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/Jobs.cpp:447
#2  0x00005555558d0188 in AIJH::AIConstruction::ExecuteJobs (this=0x55555e6968d0, limit=40)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIConstruction.cpp:120
#3  0x00005555558a3e0d in AIJH::AIPlayerJH::ExecuteAIJob (this=this@entry=0x5555561d7a70)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:819
#4  0x00005555558aee4f in AIJH::AIPlayerJH::RunGF (this=this@entry=0x5555561d7a70, gf=185802, gfisnwf=gfisnwf@entry=true)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:203
#5  0x0000555555650f9b in GameClient::NextGF (this=this@entry=0x55555623e3f0, wasNWF=wasNWF@entry=true)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:1321
#6  0x000055555565992d in GameClient::ExecuteGameFrame (this=this@entry=0x55555623e3f0)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:1259
#7  0x000055555565a01f in GameClient::Run (this=0x55555623e3f0) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:182
#8  0x00005555555cf81d in GameManager::Run (this=0x555555ac60f0)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/libs/common/include/s25util/SingletonImp.hpp:72
#9  0x00005555555bec69 in (anonymous namespace)::RunProgram (options=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/libs/common/include/s25util/SingletonImp.hpp:72
#10 0x00005555555befdc in main (argc=<optimized out>, argv=0x7fffffffdc78) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25client/s25client.cpp:440
(gdb) continue
Continuing.
Assertion failure in "ConnectFlagToRoadSytem" at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIConstruction.cpp#331: aii.GetBuildingQuality(tmpPos) == aijh.GetAINode(tmpPos).bq
``` 

replay: [2019-11-10_15-56-13.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/3828619/2019-11-10_15-56-13.rpl.zip)

**Comment by Flow86** [comment]
ok I'Ve removed the 0.9.0 milestone then
