### ISSUE TITLE
Running on Fedora s25client crashes when connecting to a remote server

### ISSUE THREAD

**Issue by awigen** [Return-To-The-Roots/s25client#1209]
Connecting to a remote game from a Fedora 31 host results in a crash. Connecting to a remote game from a Ubuntu client using the same binary works fine.

Output:
```
...
finished in 1ms
lade "share/s25rttr/RTTR/MUSIC/S2_Standard.pll"
3 in_order
Connection to 92.221.71.142:3665
Sucessfully connected to 92.221.71.142:3665
terminate called after throwing an instance of 'std::range_error'
  what():  Out of range during deserialization
```

Backtrace:
```
Thread 1 "s25client" received signal SIGABRT, Aborted.
0x00007ffff75d5625 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff75d5625 in raise () from /lib64/libc.so.6
#1  0x00007ffff75be8d9 in abort () from /lib64/libc.so.6
#2  0x00007ffff7948756 in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff79546dc in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00007ffff7954747 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00007ffff79549b9 in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0xc5d7b0 <typeinfo for std::range_error@@GLIBCXX_3.4>, dest=0x5293d0 <std::range_error::~range_error()@plt>)
    at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x00000000005c35bc in Serializer::PopUnsignedInt() ()
#7  0x00000000005c3927 in GameMessage_Player_Id::Deserialize(Serializer&) ()
#8  0x00000000008e7c95 in MessageHandler::recv(Socket&, int&, bool) ()
#9  0x00000000008e0158 in MessageQueue::recv(Socket&, bool) ()
#10 0x0000000000598906 in GameClient::Run() ()
#11 0x0000000000590cfe in GameManager::Run() ()
#12 0x00000000005870c5 in RunProgram(std::string const&, boost::program_options::variables_map&) ()
#13 0x000000000052acf9 in main ()

```

**Comment by Flamefire** [comment]
Like literally the same binary? No idea what this can cause, the code looks fine. Any chance you can debug this yourself?

**Comment by Flamefire** [comment]
BTW: Are you using latest nightly? Or which version are you using?

**Comment by awigen** [comment]
Compiling from source on Fedora 33 works, so closing this issue.
