### ISSUE TITLE
s25client crashes when loading savegame

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1284]
this is from latest git checkout:

```

Thread 1 "s25client" received signal SIGTRAP, Trace/breakpoint trap.
0x00005555557bb104 in MapNode::Deserialize (this=this@entry=0x5555595f6df0, sgd=..., numPlayers=numPlayers@entry=4, desc=..., landscapeTerrains=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/MapNode.cpp:63
63	/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/MapNode.cpp: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x00005555557bb104 in MapNode::Deserialize (this=this@entry=0x5555595f6df0, sgd=..., numPlayers=numPlayers@entry=4, desc=..., landscapeTerrains=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/MapNode.cpp:63
#1  0x00005555556ad333 in MapSerializer::Deserialize (world=..., numPlayers=4, sgd=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/world/World.h:88
#2  0x000055555568d3dc in GameWorld::Deserialize (this=this@entry=0x55555816ddc8, game=..., localgameState=..., sgd=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/world/GameWorld.cpp:96
#3  0x0000555555700841 in SerializedGameData::ReadSnapshot (this=0x5555581b5ef0, game=..., localGameState=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/SerializedGameData.cpp:265
#4  0x000055555564fe47 in GameClient::StartGame (this=this@entry=0x5555560990d0, random_init=0)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:299
#5  0x0000555555650228 in GameClient::OnGameMessage (this=0x5555560990d0, msg=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:744
#6  0x0000555555661cbd in GameMessage_Server_Start::Run (this=0x5555571a3ce0, callback=0x5555560990d0)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/GameMessages.h:220
#7  0x000055555565efc6 in GameMessage::run (this=0x5555571a3ce0, callback=0x5555560990d0, senderPlayerID=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/common/include/commonDefines.h:44
#8  0x0000555555679f41 in NetworkPlayer::executeMsgs (this=this@entry=0x555556099268, msgHandler=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/NetworkPlayer.cpp:57
#9  0x0000555555654a9d in GameClient::Run (this=0x5555560990d0) at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:186
#10 0x00005555555ca348 in GameManager::Run (this=0x7fffffffd7e0)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/external/libutil/libs/common/include/s25util/SingletonImp.hpp:72
#11 0x00005555555b988b in (anonymous namespace)::RunProgram (options=...) at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25client/s25client.cpp:470
#12 0x00005555555b9cf1 in main (argc=<optimized out>, argv=0x7fffffffdcd8) at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25client/s25client.cpp:547
```

**Comment by stefson** [comment]
this is the savegame: [Archipelag Sumary (Automatisches Speichern).sav.zip](https://github.com/Return-To-The-Roots/s25client/files/5056819/Archipelag.Sumary.Automatisches.Speichern.sav.zip)

**Comment by stefson** [comment]
I double checked today, it's working with https://github.com/Return-To-The-Roots/s25client/commit/cd8e78bc43a196097e507773f42290dc8a4e1f6f

that means it's caused by https://github.com/Return-To-The-Roots/s25client/pull/1277

I see that it's unfinished work, so I just leave you alone for now! ;-)
