### ISSUE TITLE
failed to load savegame with latest git (follow up issue)

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1332]
I just compiled the latest git version from b14a405b56bb55b805c20952c964c8cf85bde145, and it crashes when I try to load a saved game:

client state changed to stop
Connection to 127.0.0.1:3.665
Successfully connected to localhost:3.665
SERVER: Using gameframe length of 50ms
SERVER: Using networkframe length of 1 GFs (50ms)
s25client: /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/external/libutil/libs/common/src/Serializer.cpp:105: bool Serializer::PopBool(): Zusicherung »value == 0 || value == 1« nicht erfüllt.
Abgebrochen

here is a backtrace when compiled with clang-10; also please note that the backtrace escalates into libc, for which I had to set up debug symbols first and can't recall I ever had to for this project: 

```

Successfully connected to localhost:3.665
SERVER: Using gameframe length of 50ms
SERVER: Using networkframe length of 1 GFs (50ms)
s25client: /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/external/libutil/libs/common/src/Serializer.cpp:105: bool Serializer::PopBool(): Zusicherung »value == 0 || value == 1« nicht erfüllt.

Thread 1 "s25client" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff7d54536 in __GI_abort () at abort.c:79
#2  0x00007ffff7d5441f in __assert_fail_base (fmt=0x7ffff51be583 "%s%s%s:%u: %s%sZusicherung »%s« nicht erfüllt.\n%n", assertion=0x7bc536 "value == 0 || value == 1", 
    file=0x7bc54f "/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/external/libutil/libs/common/src/Serializer.cpp", line=105, function=<optimized out>)
    at assert.c:92
#3  0x00007ffff7d63462 in __GI___assert_fail (assertion=0x7bc536 "value == 0 || value == 1", 
    file=0x7bc54f "/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/external/libutil/libs/common/src/Serializer.cpp", line=105, 
    function=0x7bc5c1 "bool Serializer::PopBool()") at assert.c:101
#4  0x000000000075e0f0 in Serializer::PopBool (this=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/external/libutil/libs/common/src/Serializer.cpp:105
#5  0x00000000006156b8 in nofGeologist::nofGeologist (this=0x31fab00, sgd=..., obj_id=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/figures/nofGeologist.cpp:75
#6  0x0000000000580a63 in SerializedGameData::Create_GameObject (this=0x3237470, got=<optimized out>, obj_id=4492)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/SerializedGameData.cpp:145
#7  0x00000000005826e4 in SerializedGameData::PopObject_ (this=0x3237470, got=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/SerializedGameData.cpp:454
#8  0x00000000006247a6 in SerializedGameData::PopObject<noBase> (this=0x2, got=50608)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/SerializedGameData.h:131
#9  0x000000000062481a in SerializedGameData::PopObjectContainer<std::__cxx11::list<noBase*, std::allocator<noBase*> > > (this=0x3237470, gos=..., got=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/SerializedGameData.h:237
#10 0x00000000006242d1 in MapNode::Deserialize (this=0x58e6020, sgd=..., numPlayers=3, desc=..., landscapeTerrains=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/MapNode.cpp:92
#11 0x0000000000531827 in MapSerializer::Deserialize (world=..., numPlayers=3, sgd=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/world/MapSerializer.cpp:114
#12 0x0000000000509a5f in GameWorld::Deserialize (this=0x234de48, game=..., localgameState=..., sgd=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/world/GameWorld.cpp:97
#13 0x0000000000581a8d in SerializedGameData::ReadSnapshot (this=0x3237470, game=..., localGameState=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/SerializedGameData.cpp:275
#14 0x00000000004caad1 in GameClient::StartGame (this=0xedde30, random_init=0)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:302
#15 0x00000000004cbf75 in GameClient::OnGameMessage (this=0xedde30, msg=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:747
#16 0x00000000004dd3c6 in GameMessage_Server_Start::Run (this=0x5402900, callback=0xedde30)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/GameMessages.h:222
#17 0x00000000004dc49b in GameMessage::run (this=0x5402900, callback=<optimized out>, senderPlayerID=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/GameMessage.cpp:26
#18 0x00000000004f2744 in NetworkPlayer::executeMsgs (this=0xeddf00, msgHandler=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/NetworkPlayer.cpp:57
#19 0x00000000004c9fb9 in GameClient::Run (this=0xedde30) at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:188
#20 0x0000000000446aa2 in GameManager::Run (this=0x7fffffffd6d8) at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/GameManager.cpp:118
#21 0x0000000000435118 in (anonymous namespace)::RunProgram (options=...) at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25client/s25client.cpp:476
#22 0x0000000000434ac1 in main (argc=<optimized out>, argv=<optimized out>) at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25client/s25client.cpp:553

```

**Comment by Flamefire** [comment]
Like the same cause: The data gets corrupted due to a wrong size which was just fixed. Try the new version and see if it still happens. The other savegame loads for me now

**Comment by stefson** [comment]
well, that is sort of correct since the automatic save game now loads. But the other one from the same map doesn't: [savegame.sav.zip](https://github.com/Return-To-The-Roots/s25client/files/5766889/savegame.sav.zip) , random map for completion: [Random.swd.zip](https://github.com/Return-To-The-Roots/s25client/files/5764889/Random.swd.zip)

please note, these maps and savegames are from 28.12.2020 
they were created before the big merge of today, most likely it was a checkout from https://github.com/Return-To-The-Roots/s25client/commit/d6f2f806abb1ebdd01100b682b785d605a9a9025

**Comment by stefson** [comment]
backtrace with gcc: 

```
Thread 1 "s25client" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) 
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff77ad536 in __GI_abort () at abort.c:79
#2  0x00007ffff77ad41f in __assert_fail_base (fmt=0x7ffff51be583 "%s%s%s:%u: %s%sZusicherung »%s« nicht erfüllt.\n%n", assertion=0x555555942e15 "value == 0 || value == 1", 
    file=0x555555942d70 "/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/external/libutil/libs/common/src/Serializer.cpp", line=105, function=<optimized out>)
    at assert.c:92
#3  0x00007ffff77bc462 in __GI___assert_fail (assertion=assertion@entry=0x555555942e15 "value == 0 || value == 1", 
    file=file@entry=0x555555942d70 "/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/external/libutil/libs/common/src/Serializer.cpp", line=line@entry=105, 
    function=function@entry=0x555555942dfa "bool Serializer::PopBool()") at assert.c:101
#4  0x0000555555901586 in Serializer::PopBool (this=this@entry=0x555555f71b80)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/external/libutil/libs/common/src/Serializer.cpp:105
#5  0x000055555578383b in nofGeologist::nofGeologist (this=0x555557254bc0, sgd=..., obj_id=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/figures/nofGeologist.cpp:75
#6  0x00005555556f44eb in SerializedGameData::Create_GameObject (this=this@entry=0x555555f71b80, got=got@entry=GO_Type::NofGeologist, obj_id=4492)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/SerializedGameData.cpp:145
#7  0x00005555556f5aeb in SerializedGameData::PopObject_ (this=this@entry=0x555555f71b80, got=GO_Type::NofGeologist, got@entry=GO_Type::Unknown)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/SerializedGameData.cpp:454
#8  0x0000555555796ef8 in SerializedGameData::PopObject<noBase> (got=GO_Type::Unknown, this=0x555555f71b80)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/SerializedGameData.h:129
#9  SerializedGameData::PopObjectContainer<std::__cxx11::list<noBase*, std::allocator<noBase*> > > (this=this@entry=0x555555f71b80, gos=..., got=got@entry=GO_Type::Unknown)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/SerializedGameData.h:237
#10 0x000055555579693f in MapNode::Deserialize (this=this@entry=0x55555862ff90, sgd=..., numPlayers=numPlayers@entry=3, desc=..., landscapeTerrains=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/MapNode.cpp:92
#11 0x00005555556a6d65 in MapSerializer::Deserialize (world=..., numPlayers=3, sgd=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/world/MapSerializer.cpp:114
#12 0x0000555555689e86 in GameWorld::Deserialize (this=this@entry=0x555555ed3f48, game=..., localgameState=..., sgd=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/world/GameWorld.cpp:97
#13 0x00005555556f6177 in SerializedGameData::ReadSnapshot (this=0x555555f71b80, game=..., localGameState=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/SerializedGameData.cpp:275
#14 0x000055555564b0f1 in GameClient::StartGame (this=this@entry=0x555555f03050, random_init=0)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:302
#15 0x000055555564b4bc in GameClient::OnGameMessage (this=0x555555f03050, msg=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:747
#16 0x000055555565bc6f in GameMessage_Server_Start::Run (this=0x5555573709c0, callback=0x555555f03050)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/GameMessages.h:222
#17 0x0000555555659092 in GameMessage::run (this=0x5555573709c0, callback=0x555555f03050, senderPlayerID=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/GameMessage.cpp:26
#18 0x0000555555673bad in NetworkPlayer::executeMsgs (this=this@entry=0x555555f03120, msgHandler=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/NetworkPlayer.cpp:57
#19 0x000055555564fd51 in GameClient::Run (this=0x555555f03050) at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:188
#20 0x00005555555ca10e in GameManager::Run (this=this@entry=0x7fffffffd740) at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/GameManager.cpp:118
#21 0x00005555555ba5e0 in (anonymous namespace)::RunProgram (options=...) at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25client/s25client.cpp:476
#22 0x00005555555baa4a in main (argc=<optimized out>, argv=0x7fffffffdc38) at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25client/s25client.cpp:553


```

**Comment by stefson** [comment]
this is fixed now, all six savegames that I have available here did load properly. 

I'm a bit worried though, that there are more hidden crashes. any ideas how to debug this issue further?
