### ISSUE TITLE
Opening "advanced options"

### ISSUE THREAD

**Issue by EvelRus** [Return-To-The-Roots/s25client#1701]
Hello!
I made a "random map", configured the commands, went into the add-ons and got the error
```
Connection to 127.0.0.1:3665
Successfully connected to localhost:3665
RttR crashed. Backtrace:
0x100c1aacd
0x100c08110
0x100c0b149
0x7ff801844e9d
0x8
0x100e241bf
0x100d2b0c9
0x100cec3e0
0x100c8d967
0x100c93ca4
0x1015f33ae
0x100c282ae
0x100c06de6
0x100c04950
0x7ff8014822cd
Connection to 5.9.167.129:4123
Successfully connected to debug.rttr.info:4123
```
After which the game froze completely, I had to forcefully remove the process

Return To The Roots v20240924-5d1edefdcc4617a3e59c62189ffd1ddb89bcfc2e

**Comment by stefson** [comment]
better backtrace, this happens with any map if you proceed to hit "Einstellungen ändern" right before you start to play the map. 

```
Connection to 127.0.0.1:3665
Successfully connected to localhost:3665

Thread 1 "s25client" received signal SIGSEGV, Segmentation fault.
LuaInterfaceSettings::GetAllowedChanges (this=0x0) at /var/tmp/portage/games-strategy/s25rttr-9999-r6/work/s25rttr-9999/libs/s25main/lua/LuaInterfaceSettings.cpp:166
warning: 166	/var/tmp/portage/games-strategy/s25rttr-9999-r6/work/s25rttr-9999/libs/s25main/lua/LuaInterfaceSettings.cpp: No such file or directory
(gdb) bt
#0  LuaInterfaceSettings::GetAllowedChanges (this=0x0) at /var/tmp/portage/games-strategy/s25rttr-9999-r6/work/s25rttr-9999/libs/s25main/lua/LuaInterfaceSettings.cpp:166
#1  0x000055555582b2a7 in LuaInterfaceSettings::IsChangeAllowed (this=0x0, name=..., defaultVal=false)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r6/work/s25rttr-9999/libs/s25main/lua/LuaInterfaceSettings.cpp:215
#2  0x00005555557d743f in dskGameLobby::Msg_ButtonClick (this=0x5555575a6bc0, ctrl_id=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r6/work/s25rttr-9999/libs/s25main/desktops/dskGameLobby.cpp:688
#3  0x00005555557986ef in ctrlButton::Msg_LeftUp (this=0x55555754c1c0, mc=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r6/work/s25rttr-9999/libs/s25main/controls/ctrlButton.cpp:73
#4  0x000055555578ba0a in Window::RelayMouseMessage (this=0x5555575a6bc0, msg=&virtual Window::Msg_LeftUp(MouseCoords const&), mc=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r6/work/s25rttr-9999/libs/s25main/Window.cpp:121
#5  0x00005555555c70c7 in WindowManager::Msg_LeftUp (this=0x555555c06a50, mc=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r6/work/s25rttr-9999/libs/s25main/WindowManager.cpp:379
#6  0x00007ffff7393afd in VideoSDL2::MessageLoop (this=0x555555c092f0) at /var/tmp/portage/games-strategy/s25rttr-9999-r6/work/s25rttr-9999/extras/videoDrivers/SDL2/VideoSDL2.cpp:383
#7  0x000055555559b64e in GameManager::Run (this=0x7fffffffd6b0) at /var/tmp/portage/games-strategy/s25rttr-9999-r6/work/s25rttr-9999/libs/s25main/GameManager.cpp:98
#8  0x0000555555589607 in (anonymous namespace)::RunProgram (options=...) at /var/tmp/portage/games-strategy/s25rttr-9999-r6/work/s25rttr-9999/libs/s25client/s25client.cpp:488
#9  0x00005555555864eb in main (argc=<optimized out>, argv=<optimized out>) at /var/tmp/portage/games-strategy/s25rttr-9999-r6/work/s25rttr-9999/libs/s25client/s25client.cpp:567

```

**Comment by Flamefire** [comment]
That backtrace helped a lot, thanks!
