### ISSUE TITLE
Crash in sea attack "pure virtual method called"

### ISSUE THREAD

**Issue by bluss** [Return-To-The-Roots/s25client#287]
Crash "pure virtual method called" in function `GameWorldGame::AttackViaSea`

Source location `GameWorldGame.cpp:1171`

```
No symbol table info available.
#5  0x00007ffff701a1af in __cxa_pure_virtual ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x0000000000609dd0 in GameWorldGame::AttackViaSea (this=<optimized out>, 
    player_attacker=<optimized out>, pt=..., soldiers_count=91, strong_soldiers=true)
    at /srv/jenkins/jobs/s25rttr-git/workspace/ARCH/x86_64/PLATFORM/linux/src/GameWorldGame.cpp:1171
        it = {soldier = , harbor = , distance = 114}
        attackers = std::vector of length 91, capacity 128 = {{soldier = 0x83e3880, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x83e3950, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x83e3a20, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x83e3af0, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x875ae60, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x875af30, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x875b000, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x875b0d0, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x875b1a0, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x875b270, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x875b340, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x875b410, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x8735490, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x8735560, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x872b130, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x872b200, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x872b2d0, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x872b3a0, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x872b470, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x872b540, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x872b610, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x872b6e0, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x8709960, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x8709a30, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x8709b00, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x8709bd0, 
---Type <return> to continue, or q <return> to quit---
            harbor = 0x83e2900, distance = 28}, {soldier = 0x8709ca0, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x875c780, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x875c850, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x875c920, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x875c9f0, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x875cac0, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x875cb90, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x875cc60, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x875cd30, 
            harbor = 0x83e2900, distance = 28}, {soldier = 0x8735490, 
            harbor = 0x83e6ff0, distance = 114}, {soldier = 0x8735560, 
            harbor = 0x83e6ff0, distance = 114}, {soldier = 0x872b130, 
            harbor = 0x83e6ff0, distance = 114}, {soldier = 0x872b200, 
            harbor = 0x83e6ff0, distance = 114}, {soldier = 0x872b2d0, 
            harbor = 0x83e6ff0, distance = 114}, {soldier = 0x872b3a0, 
            harbor = 0x83e6ff0, distance = 114}, {soldier = 0x872b470, 
            harbor = 0x83e6ff0, distance = 114}, {soldier = 0x872b540, 
            harbor = 0x83e6ff0, distance = 114}, {soldier = 0x872b610, 
            harbor = 0x83e6ff0, distance = 114}, {soldier = 0x872b6e0, 
            harbor = 0x83e6ff0, distance = 114}, {soldier = 0x8709960, 
            harbor = 0x83e6ff0, distance = 114}, {soldier = 0x8709a30, 
            harbor = 0x83e6ff0, distance = 114}, {soldier = 0x8709b00, 
            harbor = 0x83e6ff0, distance = 114}, {soldier = 0x8709bd0, 
            harbor = 0x83e6ff0, distance = 114}, {soldier = 0x8709ca0, 
            harbor = 0x83e6ff0, distance = 114}, {soldier = 0x8725d50, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x8744800, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x87448d0, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x87449a0, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x8744a70, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x8744b40, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86fa980, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86faa50, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86fab20, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86fabf0, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86facc0, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86d7a80, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86d7b50, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x8735490, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x8735560, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x872b130, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x872b200, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x872b2d0, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x872b3a0, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x872b470, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x872b540, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x872b610, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x872b6e0, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86e5f90, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86e6060, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86e6130, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86e6200, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86e62d0, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x8709960, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x8709a30, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x8709b00, 
---Type <return> to continue, or q <return> to quit---
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x8709bd0, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x8709ca0, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86caa20, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86caaf0, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86cabc0, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86cac90, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86cad60, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86cae30, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86caf00, 
            harbor = 0x83e5b70, distance = 140}, {soldier = 0x86cafd0, 
            harbor = 0x83e5b70, distance = 140}}
        attacked_building = 0x9477580
        counter = <optimized out>
#7  0x0000000000559deb in GameClient::ExecuteAllGCs (this=0x7adbeb0, gcs=...)
    at /srv/jenkins/jobs/s25rttr-git/workspace/ARCH/x86_64/PLATFORM/linux/src/GameClient.cpp:1640
        i = <optimized out>
#8  0x00000000005b7649 in GameClient::ExecuteGameFrame_Game (this=0x7adbeb0)
    at /srv/jenkins/jobs/s25rttr-git/workspace/ARCH/x86_64/PLATFORM/linux/src/GameClientGF_Game.cpp:51
        msg = @0x103d3e40: {<GameMessage> = {<Message> = {<Serializer> = {
                _vptr.Serializer = 0x893c10 <vtable for GameMessage_GameCommand+16>, 
                data_ = {data_ = 0x8765670 "\005", size_ = 32, capacity_ = 32}, 
                length_ = 27, pos = 27}, id_ = 1026}, player = 5 '\005'}, checksum = 0, 
          obj_cnt = 171703, obj_id_cnt = 3708395, 
          gcs = std::vector of length 1, capacity 1 = {{px = 0x86ec580}}}
        i = <optimized out>
        checksum = 31689
#9  0x000000000055dffd in GameClient::ExecuteGameFrame (this=0x7adbeb0, skipping=false)
    at /srv/jenkins/jobs/s25rttr-git/workspace/ARCH/x86_64/PLATFORM/linux/src/GameClient.cpp:1520
        currenttime = 59541
```

**Comment by bluss** [comment]
.sav that's close before: http://s000.tinyupload.com/index.php?file_id=05002820735308266011

**Comment by Flamefire** [comment]
Thanks for reporting. The bug is fixed in the next version :sparkles:

**Comment by bluss** [comment]
Nice! I'll try & verify when it hits the nightly build.

**Comment by bluss** [comment]
Seems to be fixed, could not reproduce crash from the .sav with the nightly.

**Comment by Flamefire** [comment]
Problem was that all harbours with their nearest houses were collected. Then all their soldiers were taken. So if one house was close to 2 harbours the same soldiers was taken twice. The soldier is then converted and deleted which resulted in the crash when accessing it the 2nd time.
