### ISSUE TITLE
Crash when loading/saving game

### ISSUE THREAD

**Issue by MelTraX** [Return-To-The-Roots/s25client#465]
Everytime I click the save or load buttons, the game immediately crashes:

![2016-04-30-103901_1920x1200_scrot](https://cloud.githubusercontent.com/assets/1227576/14935406/205919c0-0ec0-11e6-8b63-ab36217634f5.png)

This is the backtrace:
```
#0  0x082c65bd in ctrlEdit::SetText(std::string const&) ()
#1  0x082b5b5b in ctrlTable::DeleteAllItems() ()
#2  0x083801cf in iwSaveLoad::RefreshTable() ()
#3  0x083813f0 in iwSaveLoad::iwSaveLoad(unsigned short, std::string const&) ()
#4  0x08381609 in iwSave::iwSave() ()
#5  0x0838f2dc in iwOptionsWindow::Msg_ButtonClick(unsigned int) ()
#6  0x082cdd71 in ctrlButton::Msg_LeftUp(MouseCoords const&) ()
#7  0x081c9889 in Window::RelayMouseMessage(bool (Window::*)(MouseCoords const&), MouseCoords const&) ()
#8  0x081c7d7a in WindowManager::Msg_LeftUp(MouseCoords) ()
#9  0xb73a4132 in VideoSDL::MessageLoop() () from ./share/s25rttr/driver/video/libvideoSDL.so
#10 0x0823fa00 in GameManager::Run() ()
#11 0x081b7fa1 in RunProgram(boost::program_options::variables_map&) ()
#12 0x0810a232 in main ()
```

I'm running Lubuntu 15.04 32 bit.

I did not test with the latest version because of #443. See screenshot for revision.

It looks like it cannot populate the directory listing. The problem might be that I'm running from a read-only file system (RTTR is inside a squashfs archive) but the home directory can be written to just fine. And in either case it shouldn't just crash. :)

**Edit**: I just copied everything from the squashfs archive to /tmp and I get the same crash.

**Comment by MelTraX** [comment]
Just tried with the latest version. Works fine.
