### ISSUE TITLE
Credits are broken

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#854]
right from the menu, if clicking upon the Credits button, s25client throws a `SIGABRT`: 

```

terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

Thread 1 "s25client" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff59c1927 in __GI_abort () at abort.c:90
#2  0x00007ffff6130005 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6
#3  0x00007ffff612dc16 in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6
#4  0x00007ffff612dc61 in std::terminate() () from /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6
#5  0x00007ffff612dea3 in __cxa_throw () from /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6
#6  0x00007ffff615774f in std::__throw_logic_error(char const*) () from /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6
#7  0x0000555555712e4d in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*> (this=this@entry=0x7fffffffd210, 
    __beg=__beg@entry=0x0, __end=__end@entry=0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/bits/basic_string.tcc:212
#8  0x00005555558a0ceb in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct_aux<char const*> (
    __end=0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>, __beg=0x0, this=0x7fffffffd210)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/bits/basic_string.h:236
#9  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*> (
    __end=0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>, __beg=0x0, this=0x7fffffffd210)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/bits/basic_string.h:255
#10 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (__a=..., __s=0x0, this=0x7fffffffd210)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/bits/basic_string.h:511
#11 dskCredits::dskCredits (this=0x555558090db0) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/src/desktops/dskCredits.cpp:154
#12 0x0000555555749f77 in dskMainMenu::Msg_ButtonClick (this=<optimized out>, ctrl_id=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/src/desktops/dskMainMenu.cpp:132
#13 0x00005555558839a8 in ctrlButton::Msg_LeftUp (this=0x555557fca9c0, mc=...) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/src/controls/ctrlButton.cpp:89
#14 0x0000555555857b26 in Window::RelayMouseMessage (this=0x555557fca5a0, msg=<optimized out>, mc=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/src/Window.cpp:133
#15 0x0000555555736031 in WindowManager::Msg_LeftUp (this=0x555555dfa430, mc=...) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/src/WindowManager.cpp:429
#16 0x00007ffff2123272 in VideoSDL::MessageLoop (this=0x555555dea8e0) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/driver/video/SDL/src/VideoSDL.cpp:496
#17 0x0000555555770e26 in VideoDriverWrapper::Run (this=<optimized out>) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/src/drivers/VideoDriverWrapper.cpp:328
#18 0x00005555557188b1 in GameManager::Run (this=0x555555de35e0) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/src/GameManager.cpp:113
#19 0x000055555570fa54 in RunProgram (options=...) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/src/s25client/s25client.cpp:392
#20 0x000055555570fe0d in main (argc=1, argv=0x7fffffffdb68) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/src/s25client/s25client.cpp:447
```

**Comment by stefson** [comment]
confirmed to be fixed.
